module.exports = {
    TARG_HARVESTERS: 3,
    TARG_UPGRADERS: 3,
    TARG_BUILDERS: 3,
    TARG_REPAIRERS: 2,
    TARG_WALL_REPAIRERS: 2,
    TARG_EXTENSIONS: [0, 0, 5, 10],
    TARG_ENERGY: [0, 250, 400, 500]
}
