module.exports = {
    TARG_HARVESTERS: 5,
    TARG_UPGRADERS: 5,
    TARG_BUILDERS: 3,
    TARG_REPAIRERS: 2,
    TARG_WALL_REPAIRERS: 3,
    TARG_EXTENSIONS: [0, 0, 5, 10],
    TARG_ENERGY: [0, 250, 500, 500],
    RENEW: false,
}
